# Problem 2

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
dataset=pd.read_csv("Customer Data.csv")

In [5]:
dataset

ID   Age   Income  Gender Marital Status Buys
0    1    <21    High    Male         Single   No
1    2    <21    High    Male        Married   No
2    3  21-35    High    Male         Single  Yes
3    4    >35  Medium    Male         Single  Yes
4    5    >35     Low  Female         Single  Yes
5    6    >35     Low  Female        Married   No
6    7  21-35     Low  Female        Married  Yes
7    8    <21  Medium    Male         Single   No
8    9    <21     Low  Female        Married  Yes
9   10    >35  Medium  Female         Single  Yes
10  11    <21  Medium  Female        Married  Yes
11  12  21-35  Medium    Male        Married  Yes
12  13  21-35    High  Female         Single  Yes
13  14    >35  Medium    Male        Married   No

In [6]:
dataset=dataset.drop('ID', axis=1)
dataset

Age   Income  Gender Marital Status Buys
0     <21    High    Male         Single   No
1     <21    High    Male        Married   No
2   21-35    High    Male         Single  Yes
3     >35  Medium    Male         Single  Yes
4     >35     Low  Female         Single  Yes
5     >35     Low  Female        Married   No
6   21-35     Low  Female        Married  Yes
7     <21  Medium    Male         Single   No
8     <21     Low  Female        Married  Yes
9     >35  Medium  Female         Single  Yes
10    <21  Medium  Female        Married  Yes
11  21-35  Medium    Male        Married  Yes
12  21-35    High  Female         Single  Yes
13    >35  Medium    Male        Married   No

In [8]:
dataset.describe()

Age   Income Gender Marital Status Buys
count    14      14     14             14   14
unique    3       3      2              2    2
top     <21  Medium   Male         Single  Yes
freq      5       6      7              7    9

In [61]:
dataset.shape

(14, 5)

In [9]:
dataset['Buys'].value_counts()

Yes    9
No     5
Name: Buys, dtype: int64

In [11]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x=dataset.iloc[:,:-1]
x=x.apply(le.fit_transform)


In [12]:
x

Age   Income  Gender  Marital Status
0      1       0       1               1
1      1       0       1               0
2      0       0       1               1
3      2       2       1               1
4      2       1       0               1
5      2       1       0               0
6      0       1       0               0
7      1       2       1               1
8      1       1       0               0
9      2       2       0               1
10     1       2       0               0
11     0       2       1               0
12     0       0       0               1
13     2       2       1               0

In [15]:
y=dataset.iloc[:,-1].values

In [16]:
y

array(['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes',
       'Yes', 'Yes', 'Yes', 'No'], dtype=object)

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)


In [19]:
x_train

Age   Income  Gender  Marital Status
11     0       2       1               0
2      0       0       1               1
13     2       2       1               0
9      2       2       0               1
1      1       0       1               0
7      1       2       1               1
10     1       2       0               0
3      2       2       1               1
0      1       0       1               1
5      2       1       0               0
12     0       0       0               1

In [20]:
y_train

array(['Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No',
       'Yes'], dtype=object)

In [24]:
x_test

Age   Income  Gender  Marital Status
8     1       1       0               0
6     0       1       0               0
4     2       1       0               1

In [21]:
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier(criterion='entropy')
classifier.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [23]:
y_pred=classifier.predict(x_test)
y_pred

array(['No', 'Yes', 'No'], dtype=object)

In [26]:
# Predict value for the given Expression
#[Age<21,Income=Low,Gender=Female,Marital Status=Married]
test_x=np.array([1,1,0,0])

In [27]:
pred_y=classifier.predict([test_x])

C:\Users\sndprobin\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


In [28]:
pred_y

array(['No'], dtype=object)

In [29]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm=confusion_matrix(y_test,y_pred)
cm

array([[0, 0],
       [2, 1]], dtype=int64)

In [30]:
accuracy_score(y_test,y_pred)

0.3333333333333333

In [32]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=3)
classifier.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [33]:
y_pred=classifier.predict(x_test)
y_pred

array(['No', 'Yes', 'Yes'], dtype=object)

In [34]:
pred_y=classifier.predict([test_x])

C:\Users\sndprobin\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [35]:
pred_y

array(['No'], dtype=object)

In [36]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm=confusion_matrix(y_test,y_pred)
cm

array([[0, 0],
       [1, 2]], dtype=int64)

In [37]:
accuracy_score(y_test,y_pred)

0.6666666666666666

In [39]:
from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB()
classifier.fit(x_train,y_train)

GaussianNB()

In [40]:
y_pred=classifier.predict(x_test)
y_pred

array(['Yes', 'Yes', 'Yes'], dtype='<U3')

In [41]:
pred_y=classifier.predict([test_x])

C:\Users\sndprobin\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


In [42]:
pred_y

array(['Yes'], dtype='<U3')

In [43]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm=confusion_matrix(y_test,y_pred)
cm

array([[3]], dtype=int64)

In [44]:
accuracy_score(y_test,y_pred)

1.0

In [52]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=10)
classifier.fit(x_train,y_train)

RandomForestClassifier(n_estimators=10)

In [53]:
y_pred=classifier.predict(x_test)
y_pred

array(['No', 'Yes', 'No'], dtype=object)

In [54]:
pred_y=classifier.predict([test_x])

C:\Users\sndprobin\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [55]:
pred_y

array(['No'], dtype=object)

In [56]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm=confusion_matrix(y_test,y_pred)
cm

array([[0, 0],
       [2, 1]], dtype=int64)

In [57]:
accuracy_score(y_test,y_pred)

0.3333333333333333

# Conclusion